global:
  marketplace-ami: false
  owner: quickstart@amazon.com
  qsname: quickstart-solace-vmr
  regions:
    - ap-northeast-1
    - ap-northeast-2
    - ap-south-1
    - ap-southeast-1
    - ap-southeast-2
    - ca-central-1
    - eu-central-1
    - eu-west-1
    - eu-west-2
    - sa-east-1
    - us-east-1
    - us-east-2
    - us-west-1
    - us-west-2
  reporting: true
tests:
  2az-asia:
    parameter_input: solace-aws-ha-2az-prod.json
    template_file: solace-vmr-master.template
    regions:
      - ap-northeast-1
      - ap-northeast-2
      - ap-south-1
      - ap-southeast-1
  3az-asia:
    parameter_input: solace-aws-ha-3az-prod.json
    template_file: solace-vmr-master.template
    regions:
      - ap-southeast-2
  2az-americas:
    parameter_input: solace-aws-ha-2az-prod.json
    template_file: solace-vmr-master.template
    regions:
      - us-west-1
      - ca-central-1
      - sa-east-1
  3az-americas:
    parameter_input: solace-aws-ha-3az-prod.json
    template_file: solace-vmr-master.template
    regions:
      - us-east-1
      - us-east-2
      - us-west-2
      - ap-southeast-2
  2az-europe:
    parameter_input: solace-aws-ha-2az-prod.json
    template_file: solace-vmr-master.template
    regions:
      - eu-west-2
  3az-europe:
    parameter_input: solace-aws-ha-3az-prod.json
    template_file: solace-vmr-master.template
    regions:
      - eu-west-1
      - eu-central-1
  2az-poc:
    parameter_input: solace-aws-ha-2az-proc.json
    template_file: solace-vmr-master.template
    regions:
      - us-west-1
  3az-poc:
    parameter_input: solace-aws-ha-3az-proc.json
    template_file: solace-vmr-master.template
    regions:
      - us-east-1
