---
#    redundancy
#    no shut
#    end
- hosts: LOCALHOST

  tasks:
    - name: Redundancy no shut
      uri:
         url:              "http://{{ ANSIBLE_VMR_IP }}:{{ ANSIBLE_VMR_SEMP_PORT }}/SEMP"
         method:           GET
         user:             "{{ ANSIBLE_USERNAME }}"
         password:         "{{ lookup('env','admin_password') }}"
         body:             "<rpc semp-version='soltr/8_2VMR'>\
                           <redundancy><no><shutdown/></no></redundancy></rpc>"
         force_basic_auth: yes
         status_code:      200
         body_format:      raw
         return_content:   yes
      register: rpc_reply
      ignore_errors: True
      until: rpc_reply.content.find("code=\"ok\"") != -1
      retries: 60
      delay: 10